; PlatformIO Project Configuration File
; ESP32 + Google AI Studio (Gemini API) через Smart DNS (xbox-dns.ru)

[platformio]
default_envs = esp32dev

[common]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM10
monitor_port = COM10
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions_ota.csv
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32dev]
extends = common
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_RUNNING_CORE=1
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-exceptions
    -fno-rtti

; Окружение для unit-тестов (Unity framework на устройстве)
[env:esp32dev_test]
extends = common
test_framework = unity
build_flags =
    -D UNIT_TEST=1
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_RUNNING_CORE=1
    -Os
build_src_filter = -<*> +<../test/test_main.cpp>
